version: "1.0"
project:
  name: bodywork-test-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1 >> stage_2 >> stage_3, stage_4 >> stage_5
stages:
  stage_1:
    executable_module_path: stage_one/main.py
    cpu_request: 0.25
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
  stage_2:
    executable_module_path: stage_two/main.py
    cpu_request: 0.25
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
    requirements:
       - requests==2.24.0
  stage_3:
    executable_module_path: stage_three/main.py
    cpu_request: 0.25
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 30
      replicas: 2
      port: 5000
      ingress: true
    requirements:
      - flask==1.1.2
  stage_4:
    executable_module_path: stage_four/main.py
    cpu_request: 0.25
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 30
      replicas: 1
      port: 5000
      ingress: false
    secrets:
      USERNAME: bodywork-test-project-credentials
      PASSWORD: bodywork-test-project-credentials
    requirements:
      - flask==1.1.2
  stage_5:
    executable_module_path: stage_five/main.py
    cpu_request: 0.25
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
    requirements:
       - requests==2.24.0
logging:
  log_level: INFO
